image: node:latest

stages:
    - Lint

npm install:
    stage: .pre
    script: npm install
    artifacts:
        paths:
            - node_modules

node --check:
    stage: Lint
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    needs: [npm install]
    dependencies: [npm install]
    script: node --check server.js
    artifacts:
        paths:
            - node_modules
# TODO: Actual lint, build, test, serve
