image: node:latest

stages:
    - Serve

npm install:
    stage: .pre
    script: npm install
    artifacts:
        paths:
            - node_modules

node server.js:
    stage: Serve
    needs: [npm install]
    script:
        - node server.js
        - curl "http://localhost:3000"
